services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network
networks:
  inception_network:
    driver: bridge
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/tkirmizi/my42projects/githubRepo/inceptionGithub/data/mysql
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/tkirmizi/my42projects/githubRepo/inceptionGithub/data/wordpress
      o: bind