version: '3'

services:
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: mariadb
        restart: always
        env_file:
            - .env
        volumes:
            # gonna add
        networks:
            - inception_network
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
            container_name: wordpress
            restart: always
            env_file:
                - .env
            volumes:
                # gonna and
            depends_on:
                -mariadb
            networks:
                -inception_network
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            # gonna add
        depends_on:
            - wordpress
        networks:
            - inception_network


